#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2024 Evgeny Kazantsev <exequtic@gmail.com>
# SPDX-License-Identifier: MIT

source "$(dirname "$0")/utils"

trap '' SIGINT

[ "$1" ] && selected="$1" || selected=0

[[ $aur != true || -z $wrapper ]] && wrapper="pacman"
wrapper="${wrapper##*/}"; wrapper_sudo=$wrapper
[[ $wrapper = "pacman" ]] && wrapper_sudo="$sudoBin pacman"

returnMenu() {
    printReturn
    showOptions $selected
    exit
}

options=(
    "${ICO_MNG_OPT_01}${MNG_OPT_01}"
    "${ICO_MNG_OPT_02}${MNG_OPT_02}"
    "${ICO_MNG_OPT_03}${MNG_OPT_03}"
    "${ICO_MNG_OPT_04}${MNG_OPT_04}"
    "${ICO_MNG_OPT_05}${MNG_OPT_05}"
    "${ICO_MNG_OPT_06}${MNG_OPT_06}"
    "${ICO_MNG_OPT_07}${MNG_OPT_07}"
    "${ICO_MNG_OPT_08}${MNG_OPT_08}"
    "${ICO_MNG_OPT_09}${MNG_OPT_09}"
    "${ICO_MNG_OPT_10}${MNG_OPT_10}"
    "${ICO_MNG_OPT_11}${MNG_OPT_11}"
    "${ICO_MNG_OPT_12}${MNG_OPT_12}"
    "${ICO_MNG_OPT_13}$(gettext "Search Flatpak packages")"
    "${ICO_MNG_OPT_14}$(gettext "Uninstall Flatpak packages")"
)

showOptions() {
    clear
    tput civis

    drawMenu() {
        tput home
        for i in "${!options[@]}"; do
            if [[ $i -eq $selected ]]; then
                echo -e "$(colorize red bold $ICO_SELECT) $(colorize green bold ${options[$i]})"
            else
                echo -e "  ${options[$i]}"
            fi
        done
    }

    drawMenu

    while true; do
        read -rsn1 input
        case $input in
            A) ((selected--));;
            B) ((selected++));;
           "") break;;
        esac

        if [[ $selected -lt 0 ]]; then
            selected=$(( ${#options[@]} - 1 ))
        elif [ $selected -ge ${#options[@]} ]; then
            selected=0
        fi

        drawMenu
    done

    clear
    tput cnorm

    case $selected in
        0) fzfPreview Slq;;
        1) fzfPreview Qq;;
        2) fzfPreview Qqe;;
        3) fzfPreview Qqet;;
        4) fzfPreview Qqtd;;
        5) uninstallOrphans;;
        6) downgradePackage;;
        7) printExec -Scc; $wrapper_sudo -Scc; returnMenu;;
        8) printExec -Sc; $wrapper_sudo -Sc; returnMenu;;
        9) rebuildPython;;
        10) $scriptDir/mirrorlist true $selected;;
        11) exit;;
        12) flatpakSearch;;
        13) flatpakUninstall;;
    esac
}

fzfPreview() {
    dependencies "fzf" true

    case $1 in
        Slq) fzfExec -$1 -Si -Syu;;
          *) fzfExec -$1 -Qil -Rsn;;
    esac
}

fzfExec() {
    packages=$($wrapper $1 | fzf $fzf_settings --preview "$wrapper $2 {}")
    if [[ -z "$packages" ]]; then
        showOptions $selected
    else
        packages=$(echo "$packages" | oneLine)
        printExec $3 "$packages"
        $wrapper_sudo $3 $packages
        returnMenu
    fi
}

uninstallOrphans() {
    if [[ -n $($wrapper -Qdt) ]]; then
        printExec -Rsn "$($wrapper -Qqtd | oneLine)"
        printImportant "$MNG_WARN"; echo
        $wrapper_sudo -Rsn $($wrapper -Qqtd)
    else
        printDone "$MNG_DONE"
    fi

    returnMenu
}

downgradePackage() {
    dependencies "fzf" true
    pacman_cache_dir="$(pacman-conf CacheDir)"
    wrapper_cache_dir="$HOME/.cache/$wrapper"

    files=$(find "$pacman_cache_dir" "$wrapper_cache_dir" -type f -name "*.pkg.tar.zst" -printf "%f\n" 2>/dev/null | \
            fzf --exact --multi --layout=reverse)

    if [[ -z "$files" ]]; then
        showOptions "$selected"
        return
    fi

    file_paths=()

    for file in $files; do
        if [ -f "${pacman_cache_dir}${file}" ]; then
            file_paths+=("${pacman_cache_dir}${file}")
        else
            path=$(find "$wrapper_cache_dir" -type f -name "$file" 2>/dev/null)
            [[ -n "$path" ]] && file_paths+=("$path")
        fi
    done

    if [ ${#file_paths[@]} -gt 0 ]; then
        cache="${file_paths[*]}"
        printExec -U "$cache"
        $wrapper_sudo -U $cache
    fi

    returnMenu
}

rebuildPython() {
    [[ $wrapper = "pacman" ]] && { printDone "$MNG_DONE"; returnMenu; }
    rebuild_dir=$(find /usr/lib -maxdepth 1 -type d -name "python*.*" | oneLine)

    if [ $(echo "$rebuild_dir" | wc -w) -gt 1 ]; then
        rebuild_dir="${rebuild_dir#* }"
        rebuild_packages=$( { pacman -Qqo "$rebuild_dir" | pacman -Qqm - | oneLine; } 2>/dev/null)
        if [[ -z "$rebuild_packages" ]]; then
            printDone "$MNG_DONE"
        else
            printExec "-S --rebuild" "$rebuild_packages"
            while true; do
                printQuestion "$MNG_RESUME"; read -r answer
                case "$answer" in
                        [Yy]*) echo; break;;
                     [Nn]*|"") echo; showOptions;;
                            *)  ;;
                esac
            done
            pacman -Qqo "$rebuild_dir" | pacman -Qqm - | $wrapper -S --rebuild -
        fi
    else
        printDone "$MNG_DONE"
    fi

    returnMenu
}

flatpakSearch() {
    dependencies "fzf flatpak" true  # Check both fzf and flatpak are available

    # List all available Flatpak packages
    available_packages=$(flatpak remote-ls --app --columns=name,application,version,description,origin 2>/dev/null)

    if [[ -z "$available_packages" ]]; then
        echo "$MNG_FLATPAK_NA"
        printReturn
        showOptions $selected
        return
    fi

    # Select package to install
    selected_package=$(echo "$available_packages" | \
               fzf $fzf_settings --delimiter='\t' --prompt="$MNG_FLATPAK_PROMPT_INSTALL" \
               --preview="flatpak info {2} 2>/dev/null || echo '$MNG_FLATPAK_NO_DETAILS'" \
               --header="$MNG_FLATPAK_HEADER")

    if [[ -n "$selected_package" ]]; then
        # Extract application ID (second column in the output) - using tab delimiter
        app_id=$(echo "$selected_package" | awk -F'\t' '{print $2}')

        if [[ -n "$app_id" ]]; then
            echo "$MNG_FLATPAK_SELECTED$app_id"
            while true; do
                echo "$MNG_FLATPAK_CHOOSE_ACTION"
                echo "1) $MNG_FLATPAK_INSTALL_OPT $app_id"
                echo "2) $MNG_FLATPAK_SHOW_DETAILS_OPT"
                echo "3) $MNG_FLATPAK_BACK_OPT"
                read -r choice
                case "$choice" in
                    1)
                        echo "$MNG_FLATPAK_INSTALLING$app_id..."
                        flatpak install --noninteractive --assumeyes "$app_id"
                        echo "$MNG_FLATPAK_INSTALL_DONE"
                        read
                        showOptions $selected
                        return
                        ;;
                    2)
                        flatpak info "$app_id" 2>/dev/null
                        echo
                        printReturn
                        ;;
                    3)
                        showOptions $selected
                        return
                        ;;
                    *) echo "$MNG_FLATPAK_INVALID_CHOICE_3";;
                esac
            done
        fi
    else
        showOptions $selected
    fi
}

flatpakUninstall() {
    dependencies "fzf flatpak" true  # Check both fzf and flatpak are available

    # List installed Flatpak packages
    installed_packages=$(flatpak list --app --columns=name,application,version,active 2>/dev/null)

    if [[ -z "$installed_packages" ]]; then
        echo "$MNG_FLATPAK_NO_INSTALLED"
        printReturn
        showOptions $selected
        return
    fi

    # Select packages to uninstall
    packages_to_remove=$(echo "$installed_packages" | \
                        fzf $fzf_settings --delimiter='\t' --prompt="$MNG_FLATPAK_PROMPT_UNINSTALL" --multi \
                        --preview="flatpak info {2} 2>/dev/null || echo '$MNG_FLATPAK_NO_INFO'" \
                        --header="$MNG_FLATPAK_HEADER_UNINSTALL")

    if [[ -n "$packages_to_remove" ]]; then
        # Extract application IDs (second column) - using tab delimiter
        app_ids=$(echo "$packages_to_remove" | awk -F'\t' '{print $2}' | xargs)

        if [[ -n "$app_ids" ]]; then
            echo "$MNG_FLATPAK_SELECTED_UNINSTALL$app_ids"
            while true; do
                echo "$MNG_FLATPAK_CHOOSE_ACTION"
                echo "1) $MNG_FLATPAK_UNINSTALL_DEPS_OPT"
                echo "2) $MNG_FLATPAK_UNINSTALL_KEEP_OPT"
                echo "3) $MNG_FLATPAK_SHOW_DETAILS_OPT"
                echo "4) $MNG_FLATPAK_BACK_OPT"
                read -r choice
                case "$choice" in
                    1)
                        echo "$MNG_FLATPAK_UNINSTALLING$app_ids $MNG_FLATPAK_UNINSTALL_DEPS_OPT..."
                        flatpak uninstall --noninteractive --delete-data "$app_ids"
                        echo "$MNG_FLATPAK_UNINSTALL_DONE"
                        read
                        showOptions $selected
                        return
                        ;;
                    2)
                        echo "$MNG_FLATPAK_UNINSTALLING$app_ids $MNG_FLATPAK_UNINSTALL_KEEP_OPT..."
                        flatpak uninstall --noninteractive --keep-ref --delete-data "$app_ids"
                        echo "$MNG_FLATPAK_UNINSTALL_DONE"
                        read
                        showOptions $selected
                        return
                        ;;
                    3)
                        for app_id in $app_ids; do
                            flatpak info "$app_id" 2>/dev/null
                            echo "---"
                        done
                        printReturn
                        ;;
                    4)
                        showOptions $selected
                        return
                        ;;
                    *) echo "$MNG_FLATPAK_INVALID_CHOICE_4";;
                esac
            done
        fi
    else
        showOptions $selected
    fi
}

showOptions
