#!/usr/bin/env bash

source "$(dirname "$0")/utils"

declare -A termArg=( ["gnome-terminal"]="--" ["ptyxis"]="--" ["terminator"]="-x" )
name="${1^}"
sess="Apdatifier"
if [[ $terminal = flatpak://* ]]; then
    flatpakTerm="${terminal#flatpak://}"
    flatpakApp="${flatpakTerm%/*}"
    term="${flatpakTerm##*/}"
else
    term="$(basename "$terminal")"
fi
termArg="${termArg[$term]:-"-e"}"
termEnv="xterm-256color"
scr="$(dirname "$0")/$1"
arg="${@:2}"

_attach="tmux attach-session -t $sess \; select-window -t $name"
_script="$scr $arg"

[[ $tmuxSession = "true" && -x $(command -v tmux) ]] && _TMUX=1

run_terminal() {
    if [[ -n $flatpakApp ]]; then
        flatpak run --command="$term" "$flatpakApp" "$termArg" flatpak-spawn --host --env=TERM="$termEnv" bash -c "$1"
    else
        "$term" "$termArg" bash -c "$1"
    fi
}
run_yakuake() {
    local command="bash -c '$1'"
    [[ -n $flatpakApp ]] && command="flatpak-spawn --host --env=TERM=$termEnv $command"
    qdbusCMD sessions runCommandInTerminal "$session" "$command"
}
create_tmux_session() {
    ! tmux has-session -t "$sess" 2>/dev/null && {
        tmux new-session -d -s "$sess" -n "$name" "bash -c '$scr $arg'"
    } || {
        ! tmux list-windows -t "$sess" | grep -wq "$name" && {
            tmux new-window -t "$sess:" -n "$name" "bash -c '$scr $arg'"
        }
    }
}


if [[ $term = "yakuake" ]]; then
    if [[ -n $flatpakApp ]]; then
        flatpak run "$flatpakApp" >/dev/null 2>&1 &
        for _ in {1..50}; do
            qdbusCMD sessions activeSessionId &>/dev/null && break
            sleep 0.1
        done
        qdbusCMD sessions activeSessionId &>/dev/null || exit 1
    fi
    session=$(qdbusCMD sessions addSession)
    visible=$(qdbusCMD MainWindow_1 org.qtproject.Qt.QWidget.visible)
    qdbusCMD tabs org.kde.yakuake.setTabTitle "$session" "$name"
    if (( _TMUX )); then
        create_tmux_session
        run_yakuake "$_attach"
    else
        run_yakuake "tput sc; clear; $_script"
    fi
    [[ $visible = "false" ]] && qdbusCMD window org.kde.yakuake.toggleWindowState
elif (( _TMUX )); then
    create_tmux_session
    run_terminal "$_attach"
else
    run_terminal "$_script"
fi
